### PR TITLE
add camera rotation

### PR DESCRIPTION
**Pull request by radmanplays**

### CODE REVIEW

**Comment by irv77** [comment]
YO THANKS RADMAN, I'll update it eventually with you in the credits! Been going around updating all of my projects

**Comment by irv77** [comment]
Current problem with it maybe is that personally the camera keeps trying to face down

**Comment by radmanplays** [comment]
> Current problem with it maybe is that personally the camera keeps trying to face down

it doesn't on my new xbox controller, are you sure your controller dosnt have stick drift?

**Comment by irv77** [comment]
> > Current problem with it maybe is that personally the camera keeps trying to face down
> 
> it doesn't on my new xbox controller, are you sure your controller dosnt have stick drift?

Well it's just that my controller does have one but none of my other games pick it up. The controls here might be too sensitive?

**Pull request merged**
